### ISSUE TITLE
error sample project

### ISSUE THREAD

**Issue by bobwatcherx** [AlexeyBond/turbosnake#1]
code
from turbosnake import functional_component, use_toggle
from turbosnake.ttk import tk_app, style, tk_button

@style
def red(s):
    s['foreground'] = 'red'
    s['background'] = 'red'

@style
def dynamic(s, *, state, **_):
    c = 'red' if state else 'blue'
    s['foreground'] = c
    s['background'] = c

@functional_component
def root():
    state, toggle = use_toggle()
    state1, toggle1 = use_toggle()

    tk_button(style=red, text='Red button')

    tk_button(style=dynamic, state=state, text='Dynamic button', on_click=toggle)
    tk_button(style=dynamic, state=state1, text='Dynamic button', on_click=toggle1)

if __name__ == '__main__':
    with tk_app(min_width=300, min_height=400):
        root()

```
miop@miop-HP-Convertible-x360-11-ab1XX:~/belajar/turbosnake$ python3 main.py 
Traceback (most recent call last):
  File "/home/miop/belajar/turbosnake/main.py", line 1, in <module>
    from turbosnake import functional_component, use_toggle
  File "/usr/local/lib/python3.10/dist-packages/turbosnake/__init__.py", line 1, in <module>
    from ._async import use_async_call
  File "/usr/local/lib/python3.10/dist-packages/turbosnake/_async.py", line 6, in <module>
    from ._components import Component
  File "/usr/local/lib/python3.10/dist-packages/turbosnake/_components.py", line 4, in <module>
    from collections import OrderedDict, Counter, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

```

**Comment by AlexeyBond** [comment]
Looks like some incompatibility between python versions 3.9 and 3.10. I've fixed some imports and typings, it should work fine now.
